### ISSUE TITLE
Make VegaGraphs work with AbstractGraph

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/VegaGraphs.jl#23]
I saw that VegaGraphs currently only works for `SimpleGraph` and `SimpleWeightedGraph`. Wouldn't it make more sense to allow any `AbstractGraph`? As long as this package  package only supports undirected graphs, traits could be used to restrict that.

**Comment by davibarreira** [comment]
Agreed. Some affairs made me stop with the development for sometime, but I'll be returning shortly.

**Comment by davibarreira** [comment]
Done!
