### ISSUE TITLE
Allow one to specify edge weights

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/VegaGraphs.jl#24]
Currently it looks like edge weights are  directly taken from the weights of  `SimpleWeightedGraphs`. Maybe it would make more sense if one could specify the weights that should be used. Otherwise there are some issues of some of the weights are very large or negative.

**Comment by davibarreira** [comment]
I'll take a look into it.

**Comment by davibarreira** [comment]
Actually, you can already do that with the `edge_weightfield` . Just give it an array, just like the `node_sizefield`. I just notice that the option was not in the function description, and I've just added.
